"""empty message

Revision ID: 0a2aa25adebb
Revises: bdf6309d8d1c
Create Date: 2016-03-03 22:37:40.187925

"""

# revision identifiers, used by Alembic.
revision = '0a2aa25adebb'
down_revision = 'bdf6309d8d1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
