"""upgrade

Revision ID: 0fc8b30fd04c
Revises: e0cc6b85c259
Create Date: 2016-03-02 22:26:18.523266

"""

# revision identifiers, used by Alembic.
revision = '0fc8b30fd04c'
down_revision = 'e0cc6b85c259'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
